### ISSUE TITLE
${TMPDIR:-/tmp}/zsh-${UID} not exists in macOS

### ISSUE THREAD

**Issue by zx1986** [zpm-zsh/ssh#2]
I got path like `/private/var/folders/jr/k6nz33nx24l15cnt8dp82k200000gn/T//zsh-501/`,
but it doesn't exist.

I temporary change CACHE_FILE to `CACHE_FILE="/tmp/ssh-hosts.zsh"` ,
I am still finding the root cause.

I am using antibody.
and bundle with `zpm-zsh/ssh`

---

http://zsh.sourceforge.net/Doc/Release/Parameters.html
https://www.zsh.org/mla/users/2004/msg01048.html

**Comment by grigorii-horos** [comment]
@zx1986 Sorry, I moved cache file to something like `${TMPDIR}/zsh-${UID}`, but forgot to add `mkdir` call
