### ISSUE TITLE
Formatting looks wrong for me

### ISSUE THREAD

**Issue by xaocon** [zpm-zsh/ssh#3]
The formatting is broken for me with this plugin. I'm guessing maybe it's an option I haven't set? Maybe there's actually a bug?

**Comment by grigorii-horos** [comment]
@xaocon Can you describe your issue? Or provide screenshot.

**Comment by xaocon** [comment]
Sorry for the poorly written issue. It seems to be working fine now. I'm not sure if it's because I moved where it was sourced or what. It was showing the actual format string in the completion, so I saw a number of places that started with `%F{yellow}-- %d --%f` but weren't yellow headers.
